version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["jest"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/dsantos747/letterboxd_hue_sort"