name: CI Tests
on:
  push:
    branches:
      - main
jobs:
  frontendTest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Running Frontend CI Tests"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --env=jsdom --coverage --coverageReporters=cobertura --report-dir=..

      - name: Report coverage results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh

          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./frontend/coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

  backendTest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Running Backend CI Tests"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: |
          cd backend
          go mod tidy

      - name: Run Backend Tests
        run: |
          cd backend
          go test -coverprofile=cover.out

      - name: Report coverage results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh


          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./backend/cover.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
